/**
 * Delta → Ren'Py .rpy 脚本导出器
 *
 * 利用 resolvedStates 逐行比较前一行的完整状态，
 * 只输出发生改变的部分，生成可在 Ren'Py 引擎中直接运行的合法脚本。
 *
 * 导出前会运行校验步骤（validateExportNames），
 * 确保所有引用名称与声明名称逐字符一致。
 *
 * sprite_id 现为表情 ID（如 "smile"），实际立绘图片通过 CharacterConfig → ExpressionRef → AssetItem 解析。
 */
import type { LineDelta, ResolvedLineState, CharacterConfig, AssetItem } from '@/core/types'

// --------------- 类型 ---------------

export interface ValidationError {
  lineId: string
  field: string
  value: string
  message: string
}

export interface ResolvedLookups {
  allCharIds: Set<string>
  /** expressionId → 对应的 Ren'Py image 标签（如 "smile" → "smile"） */
  expressionNames: Set<string>
  /** speaker（如 "Alice"）→ charId（如 "alice"），大小写不敏感匹配 */
  speakerToCharId: Record<string, string>
  allBgIds: Set<string>
}

// --------------- 辅助函数 ---------------

function indent(level: number, text: string): string {
  return '    '.repeat(level) + text
}

// --------------- 校验层 ---------------

export function resolveLookups(
  deltas: LineDelta[],
  characterConfigs: CharacterConfig[],
): ResolvedLookups {
  const allCharIds = new Set(characterConfigs.map((c) => c.charId))
  const expressionNames = new Set<string>()
  const speakerToCharId: Record<string, string> = {}
  const allBgIds = new Set<string>()

  // 收集所有有效表达式名
  for (const char of characterConfigs) {
    for (const expr of char.expressions) {
      expressionNames.add(expr.id)
    }
  }

  // 收集背景
  for (const delta of deltas) {
    if (delta.background?.asset_id) {
      allBgIds.add(delta.background.asset_id)
    }
  }

  // speaker 映射
  for (const delta of deltas) {
    if (delta.speaker) {
      for (const charId of allCharIds) {
        if (delta.speaker.toLowerCase() === charId.toLowerCase()) {
          speakerToCharId[delta.speaker] = charId
          break
        }
      }
    }
  }

  return { allCharIds, expressionNames, speakerToCharId, allBgIds }
}

export function validateExportNames(
  deltas: LineDelta[],
  lookups: ResolvedLookups,
  characterConfigs: CharacterConfig[],
): ValidationError[] {
  const errors: ValidationError[] = []
  const { allCharIds, speakerToCharId, allBgIds } = lookups

  // 构建 charId → 有效表达式集合
  const charExpressions: Record<string, Set<string>> = {}
  for (const char of characterConfigs) {
    charExpressions[char.charId] = new Set(char.expressions.map((e) => e.id))
  }

  for (const delta of deltas) {
    const lid = delta.line_id

    // 1) 说话人校验
    if (delta.speaker) {
      const mapped = speakerToCharId[delta.speaker]
      if (!mapped && !allCharIds.has(delta.speaker)) {
        errors.push({
          lineId: lid,
          field: 'speaker',
          value: delta.speaker,
          message: `说话人 "${delta.speaker}" 未匹配到任何角色 ID。已知角色：[${[...allCharIds].join(', ')}]。`,
        })
      }
    }

    // 2) 角色 sprite_id（表情 ID）校验
    for (const [charId, char] of Object.entries(delta.characters)) {
      if (!allCharIds.has(charId)) {
        errors.push({
          lineId: lid,
          field: 'characters.key',
          value: charId,
          message: `角色 "${charId}" 未在角色管理中找到配置。`,
        })
      }
      // 检查表情 ID 是否存在于该角色的配置中
      const validExpressions = charExpressions[charId]
      if (validExpressions && char.sprite_id && !validExpressions.has(char.sprite_id)) {
        const available = [...validExpressions].join(', ')
        errors.push({
          lineId: lid,
          field: 'characters.sprite_id',
          value: char.sprite_id,
          message: `表情 "${char.sprite_id}" 不在角色 "${charId}" 的表情列表中。可用表情：[${available}]。`,
        })
      }
    }

    // 3) 背景校验
    if (delta.background?.asset_id && !allBgIds.has(delta.background.asset_id)) {
      errors.push({
        lineId: lid,
        field: 'background.asset_id',
        value: delta.background.asset_id,
        message: `背景 "${delta.background.asset_id}" 不在已知背景列表中。`,
      })
    }
  }

  return errors
}

export function formatValidationErrors(errors: ValidationError[]): string {
  const header = `导出校验失败 · ${errors.length} 处问题\n${'─'.repeat(40)}`
  const body = errors.map((e, i) =>
    `\n[${i + 1}] 行 ${e.lineId} · ${e.field}\n    值: "${e.value}"\n    ${e.message}`,
  ).join('\n')
  return header + body
}

// --------------- script.rpy 导出 ---------------

export function exportToRpy(
  deltas: LineDelta[],
  resolvedStates: ResolvedLineState[],
  lookups: ResolvedLookups,
  scriptLabel: string = 'start',
): string {
  if (deltas.length === 0) return '# No content\n'

  const { speakerToCharId } = lookups
  const lines: string[] = []

  lines.push(`# Generated by ScriptWeaver`)
  lines.push(`# ${deltas.length} lines · ${resolvedStates.length} resolved states`)
  lines.push('')
  lines.push(`label ${scriptLabel}:`)
  lines.push('')

  let currentBg: string | null = null
  let currentChars: Record<string, { sprite_id: string; position_slot: string }> = {}
  let currentBgm: string | null = null
  let currentAmbient: string | null = null

  for (let i = 0; i < resolvedStates.length; i++) {
    const state = resolvedStates[i]
    const delta = deltas[i]
    const block: string[] = []

    // ---- 背景 ----
    const newBg = state.background?.asset_id ?? null
    if (newBg !== currentBg) {
      currentBg = newBg
      if (newBg) {
        const transition = state.background?.transition
        block.push(`scene ${newBg}`)
        if (transition && transition !== 'None') {
          block.push(`with ${transition}`)
        }
      }
    }

    // ---- 角色 ----
    const newChars: Record<string, { sprite_id: string; position_slot: string }> = {}
    for (const [charId, char] of Object.entries(state.characters)) {
      newChars[charId] = { sprite_id: char.sprite_id, position_slot: char.position_slot }
    }

    for (const charId of Object.keys(currentChars)) {
      if (!newChars[charId]) {
        block.push(`hide ${charId}`)
      }
    }

    for (const [charId, char] of Object.entries(newChars)) {
      const prev = currentChars[charId]
      if (!prev || prev.sprite_id !== char.sprite_id || prev.position_slot !== char.position_slot) {
        block.push(`show ${charId} ${char.sprite_id} at ${char.position_slot}`)
      }
    }

    // ---- BGM ----
    const newBgm = state.audio.bgm?.asset_id ?? null
    if (newBgm !== currentBgm) {
      currentBgm = newBgm
      if (newBgm) {
        const fadeIn = state.audio.bgm?.fade_in_ms ? state.audio.bgm.fade_in_ms / 1000 : 0
        if (fadeIn > 0) {
          block.push(`play music "${newBgm}" fadein ${fadeIn}`)
        } else {
          block.push(`play music "${newBgm}"`)
        }
      } else {
        block.push('stop music fadeout 1.0')
      }
    }

    // ---- 环境音 ----
    const newAmbient = state.audio.ambient?.asset_id ?? null
    if (newAmbient !== currentAmbient) {
      currentAmbient = newAmbient
      if (newAmbient) {
        const fadeIn = state.audio.ambient?.fade_in_ms ? state.audio.ambient.fade_in_ms / 1000 : 0
        if (fadeIn > 0) {
          block.push(`play sound "${newAmbient}" fadein ${fadeIn}`)
        } else {
          block.push(`play sound "${newAmbient}"`)
        }
      } else {
        block.push('stop sound')
      }
    }

    // ---- SE ----
    for (const seId of state.audio.se) {
      block.push(`play sound "${seId}"`)
    }

    // ---- Voice ----
    if (state.audio.voice) {
      block.push(`voice "${state.audio.voice}"`)
    }

    // ---- 台词 ----
    if (state.speaker) {
      const resolvedSpeaker = speakerToCharId[state.speaker] ?? state.speaker
      const escaped = state.dialogue.replace(/"/g, '\\"')
      block.push(`${resolvedSpeaker} "${escaped}"`)
    } else {
      const escaped = state.dialogue.replace(/"/g, '\\"')
      block.push(`"${escaped}"`)
    }

    if (block.length > 0) {
      if (i > 0) lines.push('')
      for (const b of block) {
        lines.push(indent(1, b))
      }
    }

    lines.push(indent(1, `# ${delta.line_id}`))
    currentChars = newChars
  }

  lines.push('')
  lines.push('    return')
  lines.push('')

  return lines.join('\n')
}

// --------------- definitions.rpy 导出 ---------------

export function exportDefinitionsRpy(
  characterConfigs: CharacterConfig[],
  assets: AssetItem[],
  positionSlots?: { id: string; anchor_x: number; anchor_y: number; anchor_point: string }[],
): string {
  const lines: string[] = []

  lines.push('# ============================================================')
  lines.push('# ScriptWeaver - definitions.rpy')
  lines.push('# 角色声明 / image 声明 / position transforms')
  lines.push('# ============================================================')
  lines.push('')

  // ---- Position Transforms（从槽位配置生成，非硬编码） ----
  const slots = positionSlots ?? []
  if (slots.length > 0) {
    lines.push('# ---- Position Transforms ----')
    for (const slot of slots) {
      lines.push(`transform ${slot.id}:`)
      lines.push(`    xalign ${slot.anchor_x}`)
      // anchor_point='center' 时角色居中于坐标点；'bottom' 为标准立绘底部对齐
      lines.push(`    yalign ${slot.anchor_y}`)
      lines.push('')
    }
  }

  // ---- Character 声明 ----
  if (characterConfigs.length > 0) {
    lines.push('# ---- Character 声明 ----')
    for (const char of characterConfigs) {
      const colorArg = char.dialogueColor ? `, color="${char.dialogueColor}"` : ''
      lines.push(`define ${char.charId} = Character("${char.displayName}"${colorArg})`)
    }
    lines.push('')
  }

  // ---- 立绘 Image 声明 ----
  const spriteAssets = assets.filter((a) => a.type === 'sprite')
  if (characterConfigs.length > 0 && spriteAssets.length > 0) {
    lines.push('# ---- 立绘 Image 声明 ----')
    for (const char of characterConfigs) {
      for (const expr of char.expressions) {
        const asset = spriteAssets.find((a) => a.id === expr.assetId)
        if (!asset) {
          lines.push(`# [缺失] image ${char.charId} ${expr.id} = "images/sprites/missing.png"`)
          continue
        }
        const baseName = asset.fileName.replace(/\.[^.]+$/, '')
        lines.push(`image ${char.charId} ${expr.id} = "images/sprites/${baseName}.png"`)
      }
    }
    lines.push('')
  }

  // ---- 背景 Image 声明 ----
  const bgAssets = assets.filter((a) => a.type === 'background')
  if (bgAssets.length > 0) {
    lines.push('# ---- 背景 Image 声明 ----')
    for (const bg of bgAssets) {
      const name = bg.id.replace('asset_bg_', '')
      lines.push(`image ${bg.id} = "images/bg/${name}.jpg"`)
    }
    lines.push('')
  }

  // ---- 音频清单 ----
  const audioAssets = assets.filter((a) => a.type === 'audio')
  if (audioAssets.length > 0) {
    lines.push('# ---- 音频素材清单（需放入 game/audio/ 目录） ----')
    for (const audio of audioAssets) {
      lines.push(`#   audio/${audio.fileName}`)
    }
    lines.push('')
  }

  lines.push('# 素材路径为默认生成，请按实际项目结构调整。')
  lines.push('')

  return lines.join('\n')
}

// --------------- 下载 ---------------

export function downloadRpy(
  deltas: LineDelta[],
  resolvedStates: ResolvedLineState[],
  characterConfigs: CharacterConfig[] = [],
  assets: AssetItem[] = [],
  positionSlots?: { id: string; anchor_x: number; anchor_y: number; anchor_point: string }[],
  scriptFilename: string = 'script.rpy',
): void {
  // Step 1: 构建映射表
  const lookups = resolveLookups(deltas, characterConfigs)

  // Step 2: 导出前校验
  const errors = validateExportNames(deltas, lookups, characterConfigs)
  if (errors.length > 0) {
    alert(formatValidationErrors(errors))
    return
  }

  // Step 3: 生成并下载
  const scriptContent = exportToRpy(deltas, resolvedStates, lookups)
  triggerDownload(scriptContent, scriptFilename)

  const defsContent = exportDefinitionsRpy(characterConfigs, assets, positionSlots)
  triggerDownload(defsContent, 'definitions.rpy')
}

function triggerDownload(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/x-renpy;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
