/**
 * Delta → Ren'Py .rpy 脚本导出器
 *
 * 利用 resolvedStates 逐行比较前一行的完整状态，
 * 只输出发生改变的部分，生成可在 Ren'Py 引擎中直接运行的合法脚本。
 */
import type { LineDelta, ResolvedLineState } from '@/core/types'

// --------------- 辅助函数 ---------------

/** 从 sprite_id 提取表情后缀（alice_smile → smile） */
function spriteSuffix(spriteId: string): string {
  const idx = spriteId.lastIndexOf('_')
  return idx > 0 ? spriteId.slice(idx + 1) : spriteId
}

/** 去除 asset_id 前缀（bg_street_dusk → street_dusk） */
function bareId(assetId: string): string {
  // 保留完整 id 供 Ren'Py image 定义查找
  return assetId
}

/** 缩进 */
function indent(level: number, text: string): string {
  return '    '.repeat(level) + text
}

// --------------- 主导出函数 ---------------

export function exportToRpy(
  deltas: LineDelta[],
  resolvedStates: ResolvedLineState[],
  scriptLabel: string = 'script_weaver_export',
): string {
  if (deltas.length === 0) return '# No content\n'

  const lines: string[] = []

  lines.push(`# Generated by ScriptWeaver`)
  lines.push(`# ${deltas.length} lines · ${resolvedStates.length} resolved states`)
  lines.push('')
  lines.push(`label ${scriptLabel}:`)
  lines.push('')

  // 当前行级的追踪状态（用于检测变化）
  let currentBg: string | null = null
  let currentChars: Record<string, { sprite_id: string; position_slot: string }> = {}
  let currentBgm: string | null = null
  let currentAmbient: string | null = null

  for (let i = 0; i < resolvedStates.length; i++) {
    const state = resolvedStates[i]
    const delta = deltas[i]
    const block: string[] = []

    // ---- 背景 ----
    const newBg = state.background?.asset_id ?? null
    if (newBg !== currentBg) {
      currentBg = newBg
      if (newBg) {
        const transition = state.background?.transition
        if (transition && transition !== 'None') {
          block.push(`scene ${bareId(newBg)}`)
          // with 语句与 scene 同级缩进，不加额外 indent
          block.push(`with ${transition}`)
        } else {
          block.push(`scene ${bareId(newBg)}`)
        }
      }
    }

    // ---- 角色出场/变化/退场 ----
    const newChars: Record<string, { sprite_id: string; position_slot: string }> = {}
    for (const [charId, char] of Object.entries(state.characters)) {
      newChars[charId] = { sprite_id: char.sprite_id, position_slot: char.position_slot }
    }

    // 退场角色
    for (const charId of Object.keys(currentChars)) {
      if (!newChars[charId]) {
        block.push(`hide ${charId}`)
      }
    }

    // 出场/变化角色
    for (const [charId, char] of Object.entries(newChars)) {
      const prev = currentChars[charId]
      if (!prev || prev.sprite_id !== char.sprite_id || prev.position_slot !== char.position_slot) {
        // 始终输出 at position（包括 center），确保脚本自文档化
        block.push(`show ${charId} ${spriteSuffix(char.sprite_id)} at ${char.position_slot}`)
      }
    }

    // ---- BGM ----
    const newBgm = state.audio.bgm?.asset_id ?? null
    if (newBgm !== currentBgm) {
      currentBgm = newBgm
      if (newBgm) {
        const fadeIn = state.audio.bgm?.fade_in_ms ? state.audio.bgm.fade_in_ms / 1000 : 0
        if (fadeIn > 0) {
          block.push(`play music "${bareId(newBgm)}" fadein ${fadeIn}`)
        } else {
          block.push(`play music "${bareId(newBgm)}"`)
        }
      } else {
        block.push('stop music fadeout 1.0')
      }
    }

    // ---- 环境音 ----
    const newAmbient = state.audio.ambient?.asset_id ?? null
    if (newAmbient !== currentAmbient) {
      currentAmbient = newAmbient
      if (newAmbient) {
        const fadeIn = state.audio.ambient?.fade_in_ms ? state.audio.ambient.fade_in_ms / 1000 : 0
        if (fadeIn > 0) {
          block.push(`play sound "${bareId(newAmbient)}" fadein ${fadeIn}`)
        } else {
          block.push(`play sound "${bareId(newAmbient)}"`)
        }
      } else {
        block.push('stop sound')
      }
    }

    // ---- SE（一次性音效）----
    for (const seId of state.audio.se) {
      block.push(`play sound "${bareId(seId)}"`)
    }

    // ---- Voice ----
    if (state.audio.voice) {
      block.push(`voice "${bareId(state.audio.voice)}"`)
    }

    // ---- 台词 ----
    if (state.speaker) {
      const escaped = state.dialogue.replace(/"/g, '\\"')
      block.push(`${state.speaker} "${escaped}"`)
    } else {
      const escaped = state.dialogue.replace(/"/g, '\\"')
      block.push(`"${escaped}"`)
    }

    // 输出该行内容
    if (block.length > 0) {
      // 在非首行且内容较多时加空行分隔
      if (i > 0) lines.push('')
      for (const b of block) {
        lines.push(indent(1, b))
      }
    }

    // 注释行号（调试用）
    lines.push(indent(1, `# ${delta.line_id}`))

    // 更新追踪状态
    currentChars = newChars
  }

  lines.push('')
  lines.push('    return')
  lines.push('')

  return lines.join('\n')
}

/** 触发生成并下载 .rpy 文件 */
export function downloadRpy(
  deltas: LineDelta[],
  resolvedStates: ResolvedLineState[],
  filename: string = 'script.rpy',
): void {
  const content = exportToRpy(deltas, resolvedStates)
  const blob = new Blob([content], { type: 'text/x-renpy;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
